USE qlns;
CREATE TABLE CHUCVU (
    TENCHUCVU NVARCHAR(100) PRIMARY KEY NOT NULL
);
CREATE TABLE PHONGBAN (
    MAPB VARCHAR(10) PRIMARY KEY,
    TENPB NVARCHAR(100) NOT NULL
);
CREATE TABLE NHANVIEN (
    MANV VARCHAR(20) PRIMARY KEY,
    HOTEN NVARCHAR(100) NOT NULL,
    NGAYSINH DATE NOT NULL,
    QUEQUAN NVARCHAR(100) NOT NULL,
    DIACHI NVARCHAR(100) NOT NULL,
    CCCD VARCHAR(12) CHECK (LEN(CCCD) = 12 AND CCCD NOT LIKE '%[^0-9]%'),
    GIOITINH NVARCHAR(10) NOT NULL,
    SODIENTHOAI VARCHAR(10) CHECK (
        LEN(SODIENTHOAI) = 10 AND
        SODIENTHOAI NOT LIKE '%[^0-9]%' AND LIKE '0%'
    ) NOT NULL,
    EMAIL VARCHAR(100) CHECK (EMAIL LIKE '%@%.%'),
    TENCHUCVU NVARCHAR(100),
    MAPB VARCHAR(10),
    FOREIGN KEY (TENCHUCVU) REFERENCES CHUCVU(TENCHUCVU),
    FOREIGN KEY (MAPB) REFERENCES PHONGBAN(MAPB)
);
CREATE TABLE TAIKHOAN (
    TENDN VARCHAR(30) PRIMARY KEY,
    MK VARCHAR(30) NOT NULL,
    MANV VARCHAR(20),
    FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
);
