USE qlns;
CREATE TABLE CHUCVU (
    TENCHUCVU NVARCHAR(100) PRIMARY KEY NOT NULL
);
CREATE TABLE PHONGBAN (
    MAPB VARCHAR(10) PRIMARY KEY,
    TENPB NVARCHAR(100) NOT NULL
);
CREATE TABLE NHANVIEN (
    MANV VARCHAR(20) PRIMARY KEY,
    HOTEN NVARCHAR(100) NOT NULL,
    NGAYSINH DATE NOT NULL,
    QUEQUAN NVARCHAR(100) NOT NULL,
    DIACHI NVARCHAR(100) NOT NULL,
    CCCD VARCHAR(12) NOT NULL CHECK (ISNUMERIC(CCCD) = 1),
    GIOITINH NVARCHAR(5) NOT NULL,
    SODIENTHOAI VARCHAR(10) NOT NULL CHECK (SODIENTHOAI LIKE '0%' AND ISNUMERIC(SODIENTHOAI) = 1),
    EMAIL VARCHAR(100),
    TENCHUCVU NVARCHAR(100),
    MAPB VARCHAR(10),
    FOREIGN KEY (TENCHUCVU) REFERENCES CHUCVU(TENCHUCVU),
    FOREIGN KEY (MAPB) REFERENCES PHONGBAN(MAPB)
);
CREATE TABLE TAIKHOAN (
    TENDN VARCHAR(30) PRIMARY KEY,
    MK VARCHAR(30) NOT NULL,
    MANV VARCHAR(20),
    FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
);